### ISSUE TITLE
Load error 17

### ISSUE THREAD

**Issue by zohaibtariq** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#1]
[AMXX] Load error 17 (invalid file format or version) (plugin "amx_super-cmdmanager.amxx")
[AMXX] Load error 17 (invalid file format or version) (plugin "amx_super-fun.amxx")
[AMXX] Load error 17 (invalid file format or version) (plugin "amx_super-menu.amxx")
[AMXX] Load error 17 (invalid file format or version) (plugin "amx_super-others.amxx")
[AMXX] Load error 17 (invalid file format or version) (plugin "amx_super-serious.amxx")

**meta version** 

Metamod v1.21-am  2013-03-15 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Mar 15 2013, 15:20:21  (msc optimized)

**amxx version**
AMX Mod X 1.8.2 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Feb 14 2013, 00:56:37
Build ID: 1.8.2 61:2ae84f7c0a97
Core mode: JIT+ASM32

**enabled modules**
fun
engine
fakemeta
geoip
sockets
regex
nvault
cstrike
csx
hamsandwich

**plugins.ini enteries**
amx_super-cmdmanager.amxx
amx_super-fun.amxx
amx_super-menu.amxx
amx_super-others.amxx
amx_super-serious.amxx

**as mentioned in FAQ i have checked all files are present in plugins directory as well.**

still it shows load error

downloaded cs form here.

every other plugin is working fine tried with disabling all other 3rd plugins as well

whenever i do 
amx_supermenu

it says unknown command
====================================

**amxx plugins**
Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
 [  9] Teleport Menu           1.8.2       AMXX Dev Team     telemenu.amxx    running  
 [ 10] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
 [ 11] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running  
 [ 12] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
 [ 13] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running  
 [ 14] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
 [ 15] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running  
 [ 16] Nextmap Chooser         1.8.2       AMXX Dev Team     mapchooser.amxx  running  
 [ 17] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running  
 [ 18] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running  
 [ 19] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running  
 [ 20] Restrict Weapons        1.8.2       AMXX Dev Team     restmenu.amxx    running  
 [ 21] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running  
 [ 22] CS Misc. Stats          1.8.2       AMXX Dev Team     miscstats.amxx   running  
 [ 23] CS Stats Logging        1.8.2       AMXX Dev Team     stats_logging.a  running  
 [ 24] AINO Commands           2.0         AMX(x) Community  admin_allinone.  running  
 [ 25] Stealth Shoes           2.0         AssKicR           stealth_shoes.a  running  
 [ 26] Instant AutoTeamBalanc  1.2.0       ConnorMcLeod      instant_autotea  running  
 [ 27] Unlimited Ammo          0.3.1       v3x               amx_ammo.amxx    running  
 [ 28] Amx HP                  0.1         MagicShot         amx_advanced_hp  running  
 [ 29] Admin Spectator ESP     1.3         KoST              admin_spec_esp.  running  
 [ 30] C4 Taker                1.09        hellmonja & Haml  c4_taker.amxx    running  
 [ 31] Admin Cheater Menu      3.0         te$co             admin_cheat.amx  running  
 [ 32] (Team-)Semiclip         1.2         SchlumPF*         team-semiclip.a  running  
 [ 33] Admin Slash             1.2         mike_cao          admin_slash.amx  running  
 [ 34] High Ping Kicker        1.0         Shadow/Bo0m!      amx_hpk.amxx     running  
 [ 35] unknown                 unknown     unknown           amx_super-cmdma  bad load 
 [ 36] unknown                 unknown     unknown           amx_super-fun.a  bad load 
 [ 37] unknown                 unknown     unknown           amx_super-menu.  bad load 
 [ 38] unknown                 unknown     unknown           amx_super-other  bad load 
 [ 39] unknown                 unknown     unknown           amx_super-serio  bad load 
( 35) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-cmdmanager.amxx")
( 36) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-fun.amxx")
( 37) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-menu.amxx")
( 38) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-others.amxx")
( 39) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-serious.amxx")
39 plugins, 34 running

==================================

**meta list**
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.8.2    ini  Start ANY  
 [ 2] Fun              RUN   -    fun_amxx.dll      v1.8.2    pl1  ANY   ANY  
 [ 3] Engine           RUN   -    engine_amxx.dll   v1.8.2    pl1  ANY   ANY  
 [ 4] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.8.2    pl1  ANY   ANY  
 [ 5] CStrike          RUN   -    cstrike_amxx.dll  v1.8.2    pl1  ANY   ANY  
 [ 6] CSX              RUN   -    csx_amxx.dll      v1.8.2    pl1  ANY   ANY  
 [ 7] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl1  ANY   ANY  
7 plugins, 7 running

**I show every thing which i can please fix this or let me know what should i do now? .**

**Comment by yamikaitou** [comment]
We do not support No-Steam versions of the game. Go buy and use the real game
