### ISSUE TITLE
[ISSUE] Can't turn off leave message

### ISSUE THREAD

**Issue by Veal-Uneasily4** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#11]
I set this:
amx_leave_message_enable 0
but it still shows when someone leaves.

Also, it says this in console after every map change:

[amx_super-menu.amxx] Can't add menu item "AMX_Super Menu" from plugin "AMX_Super Menu" to menu set because the Menus Front-End plugin itself is not loaded!

**Comment by xLeviNx** [comment]
Please follow the format for issues. This helps us
