### ISSUE TITLE
Not really a bug, just a question regarding join message settings.

### ISSUE THREAD

**Issue by Fiercetree** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#12]
When players enter into the server, I get the join message on the left side of the screen. At times, my setting in AMX Mod X 1.9 (which shows the most disruptive player may appear in the same area of the join message from the Super program. 
Is there any way I could configure the join message to appear somewhere else on the screen, perhaps higher above the disruptive message, so they don't overlap, maybe directly below the radar in the the upper left. The leave message does appear to be an area that doesn't overlap with the disruptive message, so it's fine. Thanks for any info!

**Comment by xLeviNx** [comment]
> When players enter into the server, I get the join message on the left side of the screen. At times, my setting in AMX Mod X 1.9 (which shows the most disruptive player may appear in the same area of the join message from the Super program. Is there any way I could configure the join message to appear somewhere else on the screen, perhaps higher above the disruptive message, so they don't overlap, maybe directly below the radar in the the upper left. The leave message does appear to be an area that doesn't overlap with the disruptive message, so it's fine. Thanks for any info!

You can change the hud message location in the source

**Comment by Fiercetree** [comment]
Could you be more specific? Is it in one of the scripting folders?

**Comment by xLeviNx** [comment]
Edit the position on this 

https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/blob/8bd7ac5c52dc0e70d39d829581386ba456f0cd49/scripting/amx_super-others.sma#L644

https://www.amxmodx.org/api/amxmodx/set_hudmessage

**Comment by Fiercetree** [comment]
> Edit the position on this
> 
> https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/blob/8bd7ac5c52dc0e70d39d829581386ba456f0cd49/scripting/amx_super-others.sma#L644
> 
> https://www.amxmodx.org/api/amxmodx/set_hudmessage

Thanks a lot for this info! Really sorry to bug you again. But I'm totally new with this. I tried changing the 0.55 entry (which I assume is the y axis, in order to make the message much higher on the screen, but to remain on the same side) to several different values, such as 0.75, 0.90, 0.25, -0.55, even 500, but the message stays in the same area. Stupid question, but do I need to recompile? Or did I get the values wrong?

**Comment by Rosenstein** [comment]
Yes, recompiling is required.

**Comment by xLeviNx** [comment]
> > Edit the position on this
> > https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/blob/8bd7ac5c52dc0e70d39d829581386ba456f0cd49/scripting/amx_super-others.sma#L644
> > 
> > https://www.amxmodx.org/api/amxmodx/set_hudmessage
> 
> Thanks a lot for this info! Really sorry to bug you again. But I'm totally new with this. I tried changing the 0.55 entry (which I assume is the y axis, in order to make the message much higher on the screen, but to remain on the same side) to several different values, such as 0.75, 0.90, 0.25, -0.55, even 500, but the message stays in the same area. Stupid question, but do I need to recompile? Or did I get the values wrong?

As Rosenstein stated, yes you do

**Comment by Fiercetree** [comment]
> > > Edit the position on this
> > > https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/blob/8bd7ac5c52dc0e70d39d829581386ba456f0cd49/scripting/amx_super-others.sma#L644
> > > 
> > > https://www.amxmodx.org/api/amxmodx/set_hudmessage
> > 
> > 
> > Thanks a lot for this info! Really sorry to bug you again. But I'm totally new with this. I tried changing the 0.55 entry (which I assume is the y axis, in order to make the message much higher on the screen, but to remain on the same side) to several different values, such as 0.75, 0.90, 0.25, -0.55, even 500, but the message stays in the same area. Stupid question, but do I need to recompile? Or did I get the values wrong?
> 
> As Rosenstein stated, yes you do

Thanks alot guys! It worked great.
