### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by MatiasGFaria** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#3]
**[I need to solve this problem]**

Hello, good day, install the amx super menu. Being the owner of the server, I enter without problems, but when a user wants to enter the server, it won't let me, I checked long's but I don't get any errors!

**Comment by xLeviNx** [comment]
> rcon meta version
> rcon meta list
> rcon amxx version
> rcon amxx plugins
> rcon status

Did you follow the format? Do the above, copy and paste the output and post it here.

**Comment by MatiasGFaria** [comment]
I do not understand what you want to get, I just want them to tell me because it removes the user from the server or not when I activate the super amx plugin, nothing else!

**Comment by xLeviNx** [comment]
Copy each command and then it should show up in your console with data related to that underneath it. Copy and paste that here. 

Also AMX super has nothing related to kicking users for no reason so it has to be something else causing it. 

Can’t help you until you do what I sent. Then I can further see what it can be and help you out.

**Comment by MatiasGFaria** [comment]
**meta version:**
Metamod v1.21.1-am  2013-09-26 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Sep 26 2013, 17:09:41 -0500 (optimized)

 **meta list**
Currently loaded plugins:
      description      stat pend  file              vers      src  load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.9.0.5  ini  Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.0.1  ini  Start Never
 [ 3] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2017RC5  ini  ANY   ANY  
 [ 4] HLGuard          RUN   -    hlguard_mm_tinti  v1.9.t20  ini  Chlvl Chlvl
 [ 5] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.9.0.5  pl1  ANY   ANY  
 [ 6] CStrike          RUN   -    cstrike_amxx_i38  v1.9.0.5  pl1  ANY   ANY  
 [ 7] Engine           RUN   -    engine_amxx_i386  v1.9.0.5  pl1  ANY   ANY  
 [ 8] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.9.0.5  pl1  ANY   ANY  
 [ 9] Fun              RUN   -    fun_amxx_i386.so  v1.9.0.5  pl1  ANY   ANY  
 [10] CSX              RUN   -    csx_amxx_i386.so  v1.9.0.5  pl1  ANY   ANY  
 [11] MySQL            RUN   -    mysql_amxx_i386.  v1.9.0.5  pl1  ANY   ANY  
11 plugins, 11 running

**amxx version**

AMX Mod X 1.9.0.5271 (http://www.amxmodx.org)
Authors:
	David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
	Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
	Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
	Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Jun 24 2020 13:53:30
Built from: https://github.com/alliedmodders/amxmodx/commit/5eea3e5
Build ID: 5271:5eea3e5
Core mode: JIT+ASM32

**amxx plugins**

Currently loaded plugins:
       name                    version     author            file             status   
 [  1] Admin Base              1.9.0.5271  AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.9.0.5271  AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.9.0.5271  AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.9.0.5271  AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.9.0.5271  AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.9.0.5271  AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.9.0.5271  AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.9.0.5271  AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.9.0.5263  AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.9.0.5271  AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.9.0.5271  AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.9.0.5271  AMXX Dev Team     antiflood.amxx   running  
 [ 13] Scrolling Message       1.9.0.5271  AMXX Dev Team     scrollmsg.amxx   running  
X[ 14] Info. Messages          1.9.0.5271  AMXX Dev Team     imessage.amxx    running   [ 15] Admin Votes             1.9.0.5271  AMXX Dev Team     adminvote.amxx   running  
 [ 16] NextMap                 1.9.0.5271  AMXX Dev Team     nextmap.amxx     stopped  
 [ 17] Pause Plugins           1.9.0.5271  AMXX Dev Team     pausecfg.amxx    running  
 [ 18] Stats Configuration     1.9.0.5271  AMXX Dev Team     statscfg.amxx    running  
 [ 19] Advanced Spam Protecti  4.5.1       Souvik            ASP.amxx         running  
 [ 20] Admin Models            1.2         DanielR           Admin_Models.am  debug    
 [ 21] AFK: Transfer Spec      1.3         Wilian M.         afk_transfer_sp  running  
 [ 22] AMX Super Cmd Manager   5.0.2       SuperCentral.co   amx_super-cmdma  running  
 [ 23] Amx Super Fun           5.0.2       SuperCentral.co   amx_super-fun.a  running  
 [ 24] AMX_Super Menu          5.0.2       SuperCentral.co   amx_super-menu.  running  
 [ 25] Amx Super Others        5.0.2       SuperCentral.co   amx_super-other  running  
 [ 26] Amx Super Serious       5.0.2       SuperCentral.co   amx_super-serio  running  
 [ 27] Team Semiclip           2.0.0       schmurgel1983     cs_team_semicli  running  
 [ 28] CS Revo: Anti IP        1.0         Wilian M.         csrevo_anti_ip.  running  
X[ 29] CS Revo: Paraquedas Li  1.0         Wilian M.         csr_parachute_l  running   [ 30] CS Revo: Back Weapons   2.0         hoboman313/cheap  csr_backweapons  running  
 [ 31] Bomb Countdown HUD Tim  0.2         SAMURAI           C4Plugin.amxx    running  
 [ 32] Talk dead               1.0.1       www.4evergaming.  deadtalk.amxx    running  
 [ 33] DatearCincoYA           2.1         CincoYA.net       datear.amxx      running  
 [ 34] Best Player of the Rou  1.0         hleV              ElMejorRound.am  running  
 [ 35] Knife Duel              1.0         Alka              knife_duel.amxx  running  
 [ 36] Galileo                 v5.9.1-926  Brad Jones/Addon  galileo.amxx     debug    
 [ 37] HeadShot Sounds         0.2         ConnorMcLeod      headshots_sound  running  
 [ 38] Info.Admin              1.0         Skylar            Info-Admin.amxx  debug    
 [ 39] Menu Basico             1.0         [Anti]            Menu.amxx        running  
 [ 40] mute menu               1.0         cheap_suit        MenuMute.amxx    running  
 [ 41] Mix Maker               10.0        #8 SickneSS       Mix_Maker.amxx   running  
 [ 42] Mix Selection           1.0         Neeeeeeeeeel.-    MixCapitan.amxx  running  
 [ 43] mafiacs                 13          mafiacs           mafiacs_1.amxx   debug    
X[ 44] StatsX                  1.9.0.5270  AMXX Dev Team     NuevoTop.amxx    running   [ 45] Pedido de ADMINS        1.0         Chema             PedidoYa.amxx    running  
 [ 46] Player Connecting and   1.5         SoundBlaster      PlayerConnect.a  running  
 [ 47] Autoresponder/Advertis  0.5         MaximusBrood      reklamy.amxx     running  
 [ 48] Reset Score             1.0                           Reset_Score.amx  running  
 [ 49] VIP Eng Version         3.0         Dunno             Vip.amxx         running  
 [ 50] VIPScore                1.0         ~] SB [~          vip_score.amxx   debug    
 [ 51] WalkGuard               1.3.2       mogel             walkguard.amxx   running  
 [ 52] Admin Prefixes          4.0 WHITE   m0skVi4a ;]       AdminPrefixes_W  running  
 [ 53] Advanced Vault System   1.5         Destro            adv_vault.amxx   running  

**status**

hostname:  DeathRow | MIX FRUTERO | #Arg
version :  48/1.1.2.7/Stdio 2186 secure  (10)
tcp/ip  :  45.235.98.30:27315
map     :  de_dust2_largo at: 0 x, 0 y, 0 z
players :  1 active (12 max)

#      name userid uniqueid frag time ping loss adr
# 1 "Titanium tf." 18 STEAM_0:0:135378624   0 03:55   34    0 181.98.105.15:27005
1 users

**Comment by MatiasGFaria** [comment]
Any solution?

**Comment by xLeviNx** [comment]
Well, you are using non-steam so we don't support that.
As for your issue, it is not related to our plugin, as it is related to your other plugins and modules.

**Comment by MatiasGFaria** [comment]
so what solution do you give me?
