### ISSUE TITLE
AMX SUPER plugin amx_super-serious.amxx problem

### ISSUE THREAD

**Issue by H0WL1234** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#4]
I installed amx super when I want to join a team I cannot and still I stay spectator. then I found out that the problem is with amx_super-serious.amxx so decided to disable this plugin and I could join teams. what to do about amx_super-serious.amxx ?

vid : https://streamable.com/ru8stf

**Comment by xLeviNx** [comment]
Follow the template provided to you. 

# Show the output of the following:
> version
> meta version
> meta list
> amxx version
> amxx plugins
> status

## Add rcon if you're doing it from inside the server, via console. Meaning enter the server, open console. Type your password into rcon_password, and then run the above commands as:

> rcon meta version
> rcon meta list
> rcon amxx version
> rcon amxx plugins
> rcon status

### Provide error logs from amxmodx/logs/error_  and post them in code tags or upload to either hastebin/pastebin with an appropriate link.

**Comment by H0WL1234** [comment]
Where should I put the  ?
version
meta version
meta list
amxx version
amxx plugins
status

**Comment by xLeviNx** [comment]
I really suggest you read what I sent you.

**Comment by H0WL1234** [comment]
Version of AMX SUPER IS 5.0.2

Metamod version is 1.21.0.37


] meta list 
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] dproto_EF        fail load  dproto.dll        v0.9.356  ini   Start Never
 [ 2] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.8.2    ini   Start ANY  
 [ 3] Fun              RUN   -    fun_amxx.dll      v1.8.2    pl2   ANY   ANY  
 [ 4] CStrike          RUN   -    cstrike_amxx.dll  v1.8.2    pl2   ANY   ANY  
 [ 5] CSX              RUN   -    csx_amxx.dll      v1.8.2    pl2   ANY   ANY  
 [ 6] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.8.2    pl2   ANY   ANY  
 [ 7] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl2   ANY   ANY  
 [ 8] Engine           RUN   -    engine_amxx.dll   v1.8.2    pl2   ANY   ANY  
8 plugins, 7 running

amxx version : I did not install the amxmodx because I am using CS 1.6 warzone and It already has the amxmodx.

amxx plugins : the screen shot >>> https://ibb.co/3T6hJqX

status : I did not understand about this , what do you mean exactly ?

**Comment by yamikaitou** [comment]
No-Steam is not supported

**Comment by H0WL1234** [comment]
but the plugin worked currect when I disabled amx_super-serious.amxx

**Comment by yamikaitou** [comment]
Cool, we don't provide support to people who use No-Steam

**Comment by H0WL1234** [comment]
ok thank U :D
