### ISSUE TITLE
amx_super-others crashing Counterstrike CZ server (players freezing in spawn)

### ISSUE THREAD

**Issue by HEXAGONENTERTAINMENT** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#5]
# Show the output of the following:
> version
 AMX-Super-5.0.2
> meta version
Metamod v1.21-am
> meta list
win32 addons/amxmodx/dlls/amxmodx_mm.dll
linux addons/amxmodx/dlls/amxmodx_mm_i386.so
> amxx version
1.8.3-dev-git5134  (this is autoinstalled by the hosting service (NFO) and they cannot change it until a new AMXMODX version is OFFICIALLY released)
> amxx plugins
Admin Base         1.8.3-dev+  AMXX Dev Team     admin.amxx       running  
Admin Commands     1.8.3-dev+  AMXX Dev Team     admincmd.amxx    running  
Admin Help         1.8.3-dev+  AMXX Dev Team     adminhelp.amxx   running  
Slots Reservation  1.8.3-dev+  AMXX Dev Team     adminslots.amxx  running  
Multi-Lingual Sys  1.8.3-dev+  AMXX Dev Team     multilingual.am  running  
Menus Front-End    1.8.3-dev+  AMXX Dev Team     menufront.amxx   running  
Commands Menu      1.8.3-dev+  AMXX Dev Team     cmdmenu.amxx     running  
Players Menu       1.8.3-dev+  AMXX Dev Team     plmenu.amxx      running  
Maps Menu          1.8.3-dev+  AMXX Dev Team     mapsmenu.amxx    running  	
Plugin Menu        1.8.3-dev+  AMXX Dev Team     pluginmenu.amxx  running

Admin Chat         1.8.3-dev+  AMXX Dev Team     adminchat.amxx   running  
Anti Flood         1.8.3-dev+  AMXX Dev Team     antiflood.amxx   running  
Scrolling Message  1.8.3-dev+  AMXX Dev Team     scrollmsg.amxx   running  
Info. Messages     1.8.3-dev+  AMXX Dev Team     imessage.amxx    running  
NextMap            1.8.3-dev+  AMXX Dev Team     nextmap.amxx     running  
TimeLeft           1.8.3-dev+  AMXX Dev Team     timeleft.amxx    running  
Pause Plugins      1.8.3-dev+  AMXX Dev Team     pausecfg.amxx    running  
Stats Configurati  1.8.3-dev+  AMXX Dev Team     statscfg.amxx    running  
StatsX             1.8.3-dev+  AMXX Dev Team     statsx.amxx      running  
HLstatsX CE Ingam  1.6.18 (HL  psychonic         hlstatsx_comman  running

Autoresponder/Adv  0.5         MaximusBrood      ad_manager.amxx  running  
AdminListen        2.3x        /dev/ urandom     adminlisten.amx  running  
Admin Spectator E  1.3         KoST              admin_spec_esp.  running  
AFK KiSSS          3.0.0 Beta  Isobold           afkkisss.amxx    running  
Ultimate Gore      1.6         JTP10181          amx_gore_ultima  running  
High Ping Kicker   1.0         Shadow/Bo0m!      amx_hpk.amxx     running  
AMX Super Cmd Man  5.0.2       SuperCentral.co   amx_super-cmdma  running  
Amx Super Fun      5.0.2       SuperCentral.co   amx_super-fun.a  debug    
Amx Super Others   5.0.2       SuperCentral.co   amx_super-other  debug    
Amx Super Serious  5.0.2       SuperCentral.co   amx_super-serio  running

AMX_Super Menu     5.0.2       SuperCentral.co   amx_super-menu.  running  
AMX Bank           1.7         twistedeuphoria   amx_bank.amxx    running  
AMXX Spy++         1.0         [DeathTV] Sid 6.  amx_spyplusplus  running  
Automatic knife d  0.3         JGHG              automatic_knife  running  
C4 Timer           0.0.1       ConnorMcLeod      c42.amxx         running  
D.I.C.E.           1.1         OciXCrom          dice_main.amxx   running  
D.I.C.E. Items     1.1         OciXCrom          dice_items_glob  running  
D.I.C.E. Items: C  1.1         OciXCrom          dice_items_cstr  running  
Last man bets      0.9.4       JGHG              lastmanbets_nop  running  
Mirror Damage      1.0.0       EKS               mirror_damage.a  running

Team Balancer      1.8b3       Ptahhotep         ptb.amxx         running  
Quake Sounds       2.1         hleV              quakesounds.amx  running  
Reconnect Feature  0.2.4 BETA  ConnorMcLeod      reconnect_featu  running  
Restrict Weapons   1.8.3-dev+  AMXX Dev Team     restmenu.amxx    running  
Silly C4           1.2         Cheap_Suit        sillyc4.amxx     running
> status

## Add rcon if you're doing it from inside the server, via console. Meaning enter the server, open console. Type your password into rcon_password, and then run the above commands as:

> rcon meta version
Metamod v1.21-am
> rcon meta list
 [  1] AMX Mod X, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  2] Fun, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  3] Engine, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  4] FakeMeta, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  5] MySQL, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org/
 [  6] CStrike, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  7] Ham Sandwich, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  8] CSX, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org/
 [  9] GeoIP, v1.8.3-dev+5134, Aug  5 2017, by AMX Mod X Dev Team, see http://www.amxmodx.org/
> rcon amxx version
1.8.3-dev-git5134
> rcon amxx plugins
Admin Base         1.8.3-dev+  AMXX Dev Team     admin.amxx       running  
Admin Commands     1.8.3-dev+  AMXX Dev Team     admincmd.amxx    running  
Admin Help         1.8.3-dev+  AMXX Dev Team     adminhelp.amxx   running  
Slots Reservation  1.8.3-dev+  AMXX Dev Team     adminslots.amxx  running  
Multi-Lingual Sys  1.8.3-dev+  AMXX Dev Team     multilingual.am  running  
Menus Front-End    1.8.3-dev+  AMXX Dev Team     menufront.amxx   running  
Commands Menu      1.8.3-dev+  AMXX Dev Team     cmdmenu.amxx     running  
Players Menu       1.8.3-dev+  AMXX Dev Team     plmenu.amxx      running  
Maps Menu          1.8.3-dev+  AMXX Dev Team     mapsmenu.amxx    running  	
Plugin Menu        1.8.3-dev+  AMXX Dev Team     pluginmenu.amxx  running

Admin Chat         1.8.3-dev+  AMXX Dev Team     adminchat.amxx   running  
Anti Flood         1.8.3-dev+  AMXX Dev Team     antiflood.amxx   running  
Scrolling Message  1.8.3-dev+  AMXX Dev Team     scrollmsg.amxx   running  
Info. Messages     1.8.3-dev+  AMXX Dev Team     imessage.amxx    running  
NextMap            1.8.3-dev+  AMXX Dev Team     nextmap.amxx     running  
TimeLeft           1.8.3-dev+  AMXX Dev Team     timeleft.amxx    running  
Pause Plugins      1.8.3-dev+  AMXX Dev Team     pausecfg.amxx    running  
Stats Configurati  1.8.3-dev+  AMXX Dev Team     statscfg.amxx    running  
StatsX             1.8.3-dev+  AMXX Dev Team     statsx.amxx      running  
HLstatsX CE Ingam  1.6.18 (HL  psychonic         hlstatsx_comman  running

Autoresponder/Adv  0.5         MaximusBrood      ad_manager.amxx  running  
AdminListen        2.3x        /dev/ urandom     adminlisten.amx  running  
Admin Spectator E  1.3         KoST              admin_spec_esp.  running  
AFK KiSSS          3.0.0 Beta  Isobold           afkkisss.amxx    running  
Ultimate Gore      1.6         JTP10181          amx_gore_ultima  running  
High Ping Kicker   1.0         Shadow/Bo0m!      amx_hpk.amxx     running  
AMX Super Cmd Man  5.0.2       SuperCentral.co   amx_super-cmdma  running  
Amx Super Fun      5.0.2       SuperCentral.co   amx_super-fun.a  debug    
Amx Super Others   5.0.2       SuperCentral.co   amx_super-other  debug    
Amx Super Serious  5.0.2       SuperCentral.co   amx_super-serio  running

AMX_Super Menu     5.0.2       SuperCentral.co   amx_super-menu.  running  
AMX Bank           1.7         twistedeuphoria   amx_bank.amxx    running  
AMXX Spy++         1.0         [DeathTV] Sid 6.  amx_spyplusplus  running  
Automatic knife d  0.3         JGHG              automatic_knife  running  
C4 Timer           0.0.1       ConnorMcLeod      c42.amxx         running  
D.I.C.E.           1.1         OciXCrom          dice_main.amxx   running  
D.I.C.E. Items     1.1         OciXCrom          dice_items_glob  running  
D.I.C.E. Items: C  1.1         OciXCrom          dice_items_cstr  running  
Last man bets      0.9.4       JGHG              lastmanbets_nop  running  
Mirror Damage      1.0.0       EKS               mirror_damage.a  running

Team Balancer      1.8b3       Ptahhotep         ptb.amxx         running  
Quake Sounds       2.1         hleV              quakesounds.amx  running  
Reconnect Feature  0.2.4 BETA  ConnorMcLeod      reconnect_featu  running  
Restrict Weapons   1.8.3-dev+  AMXX Dev Team     restmenu.amxx    running  
Silly C4           1.2         Cheap_Suit        sillyc4.amxx     running
> rcon status
hostname:              THE HEXAGON
version :  48/1.0.0.3 8308 secure  (80)
tcp/ip  :  74.91.123.28:27015
map     :  cs_agency_csgo at: 0 x, 0 y, 0 z
players :  1 active (26 max)
### Provide error logs from amxmodx/logs/error_  and post them in code tags or upload to either hastebin/pastebin with an appropriate link.
[error_20220128.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358161/error_20220128.log)
[error_20220131.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358162/error_20220131.log)
[error_20220201.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358163/error_20220201.log)
[error_20220202.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358164/error_20220202.log)
[error_20220205.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358165/error_20220205.log)
[error_20220212.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358166/error_20220212.log)
[error_20220218.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358167/error_20220218.log)
[error_20220226.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358168/error_20220226.log)
[error_20220310.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358169/error_20220310.log)
[error_20220320.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358170/error_20220320.log)
[error_20220321.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358171/error_20220321.log)
[error_20220322.log](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/8358172/error_20220322.log)

**Comment by HEXAGONENTERTAINMENT** [comment]
Be patient please and excuse my ignorance.  I made a GITHUB account TODAY, and I am very unfamiliar with moderate or advanced coding.  All I know is what I have had to learn in order to configure this game server which is hosted on STEAM.  I have no idea how this is SUPPOSED to work here in GITHUB.  I have been running the server for a while, and prior to owning my own I was an admin on another for over 10 years.  I am familiar with some things, but this issue I am having has escaped my understanding.

**Comment by xLeviNx** [comment]
the AFK kicker on amx other and another AFK plugin is clashing. You can disable it from amx_super or use the external one


Can you post how your plugins.ini looks?

**Comment by HEXAGONENTERTAINMENT** [comment]
> 

Absolutely.   That makes sense, actually.:

```
;`` AMX Mod X plugins

; Admin Base - Always one has to be activated
admin.amxx		; admin base (required for any admin-related)
;admin_sql.amxx		; admin base - SQL version (comment admin.amxx)

; Basic
admincmd.amxx		; basic admin console commands
adminhelp.amxx		; help command for admin console commands
adminslots.amxx		; slot reservation
multilingual.amxx	; Multi-Lingual management

; Menus
menufront.amxx		; front-end for admin menus
cmdmenu.amxx		; command menu (speech, settings)
plmenu.amxx		; players menu (kick, ban, client cmds.)
;telemenu.amxx		; teleport menu (Fun Module required!)
mapsmenu.amxx		; maps menu (vote, changelevel)
pluginmenu.amxx		; Menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx		; console chat commands
antiflood.amxx		; prevent clients from chat-flooding the server
scrollmsg.amxx		; displays a scrolling message
imessage.amxx		; displays information messages
;adminvote.amxx		; vote commands

; Map related
nextmap.amxx		; displays next map in mapcycle
;mapchooser.amxx	; allows to vote for next map
timeleft.amxx		; displays time left on map

; Configuration
pausecfg.amxx		; allows to pause and unpause some plugins
statscfg.amxx		; allows to manage stats plugins via menu and commands

; Counter-Strike
;restmenu.amxx		; restrict weapons menu
statsx.amxx		; stats on death or round end (CSX Module required!)
;miscstats.amxx		; bunch of events announcement for Counter-Strike
;stats_logging.amxx	; weapons stats logging (CSX Module required!)

; Custom - Add 3rd party plugins here

hlstatsx_commands_cstrike.amxx ; HLStatsX interaction plugin
ad_manager.amxx
adminlisten.amxx
admin_spec_esp.amxx
;adminvote.amxx
afkkisss.amxx
amx_gore_ultimate.amxx
amx_hpk.amxx
amx_super-cmdmanager.amxx
amx_super-fun.amxx
amx_super-others.amxx
amx_super-serious.amxx
amx_super-menu.amxx
amx_bank.amxx
amx_spyplusplus.amxx
automatic_knife_duel.amxx
;AQS.amxx
;c42.amxx
c4timer.amxx
;changedsettings.amxx
dice_main.amxx
dice_items_global.amxx
dice_items_cstrike.amxx
lastmanbets_noprizes.amxx
;Map_Spawns_Editor.amxx
mirror_damage.amxx
;pingfaker.amxx
plmenu.amxx
ptb.amxx
quakesounds.amxx
;rank.amxx
;Realistic_FlashBang.amxx
reconnect_features.amxx
restmenu.amxx
;roll_the_dice.amxx
sillyc4.amxx
```

**Comment by xLeviNx** [comment]
Yeah, so I usually would place super plugins in the bottom of the list, but it’s definitely clashing with your afk plug-in. I would recommend disabling the afk portion of amx_super or you could just delete that portion of the plug-in and recompile. It’s your choice, but the error comes from two plugins clashing

**Comment by HEXAGONENTERTAINMENT** [comment]
Thank you for taking a look a this!
What would be the correct way to disable the AFK portion of amx_super?

**Comment by HEXAGONENTERTAINMENT** [comment]
Thank you for taking a look a this!
What would be the correct way to disable the AFK portion of amx_super?
Is it as simple as this?

```
// (En/Dis)able the AFK manager.
// 0 - Disabled
// 1 - Enabled
//
// Default value: 1
amx_afkcheck_allow 0
```

What about these?  Can I leave them because by disabling the AFK manager above it automatically disables these too by default?

```
// Time in seconds that a player has to be afk to transfer the bomb.
// 
// Default value: 15
afk_bombtransfer_time 30

// Time in seconds until an unassigned player is checked to be kicked by the AFK management.
// 
// Default value: 5
amx_immune_time 5

// Max time in seconds that a player is allowed to be afk.
//
// Default value: 45
amx_max_afktime 120
```

**Comment by HEXAGONENTERTAINMENT** [comment]
On a similar topic why do all of my logs look like this?

ie; why does it appear to load everything TWICE in a row?  Does it matter?

```
L 03/29/2022 - 12:54:43: Log file started (file "logs\L0329169.log") (game "czero") (version "48/1.0.0.3/8308")
L 03/29/2022 - 12:54:43: [META] Metamod v1.21-am  2013-03-15
L 03/29/2022 - 12:54:43: [META] by Will Day <willday@metamod.org>
L 03/29/2022 - 12:54:43: [META]    http://www.metamod.org/
L 03/29/2022 - 12:54:43: [META] compiled: Mar 15 2013, 15:20:21  (msc optimized)
L 03/29/2022 - 12:54:43: [META] engine: swds
L 03/29/2022 - 12:54:43: [META] Recognized game 'czero'; using dllfile 'mp.dll'
L 03/29/2022 - 12:54:43: [META] Game DLL for 'Counter-Strike:Condition Zero' loaded successfully
L 03/29/2022 - 12:54:43: [META] ini: Begin reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini
L 03/29/2022 - 12:54:43: [META] ini: Read plugin config for: <amxmodx_mm.dll>
L 03/29/2022 - 12:54:43: [META] ini: Finished reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini; Found 1 plugins to load
L 03/29/2022 - 12:54:43: [META] dll: Loading plugins...
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'Fun': Fun v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'Engine': Engine v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'FakeMeta': FakeMeta v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'MySQL': MySQL v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'CStrike': CStrike v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'Fun'; already loaded (status=running)
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'fun_amxx.dll'
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'Engine'; already loaded (status=running)
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'engine_amxx.dll'
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'FakeMeta'; already loaded (status=running)
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'fakemeta_amxx.dll'
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'MySQL'; already loaded (status=running)
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'mysql_amxx.dll'
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'CStrike'; already loaded (status=running)
L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'cstrike_amxx.dll'
L 03/29/2022 - 12:54:43: [META] dll: Finished loading 1 plugins
L 03/29/2022 - 12:54:43: Log file closed
```

**Comment by xLeviNx** [comment]
> Thank you for taking a look a this! What would be the correct way to disable the AFK portion of amx_super? Is it as simple as this?
> 
> ```
> // (En/Dis)able the AFK manager.
> // 0 - Disabled
> // 1 - Enabled
> //
> // Default value: 1
> amx_afkcheck_allow 0
> ```
> 
> What about these? Can I leave them because by disabling the AFK manager above it automatically disables these too by default?
> 
> ```
> // Time in seconds that a player has to be afk to transfer the bomb.
> // 
> // Default value: 15
> afk_bombtransfer_time 30
> 
> // Time in seconds until an unassigned player is checked to be kicked by the AFK management.
> // 
> // Default value: 5
> amx_immune_time 5
> 
> // Max time in seconds that a player is allowed to be afk.
> //
> // Default value: 45
> amx_max_afktime 120
> ```

Yes just disable the afkcheck and everything else won’t clash

**Comment by xLeviNx** [comment]
> On a similar topic why do all of my logs look like this?
> 
> ie; why does it appear to load everything TWICE in a row? Does it matter?
> 
> ```
> L 03/29/2022 - 12:54:43: Log file started (file "logs\L0329169.log") (game "czero") (version "48/1.0.0.3/8308")
> L 03/29/2022 - 12:54:43: [META] Metamod v1.21-am  2013-03-15
> L 03/29/2022 - 12:54:43: [META] by Will Day <willday@metamod.org>
> L 03/29/2022 - 12:54:43: [META]    http://www.metamod.org/
> L 03/29/2022 - 12:54:43: [META] compiled: Mar 15 2013, 15:20:21  (msc optimized)
> L 03/29/2022 - 12:54:43: [META] engine: swds
> L 03/29/2022 - 12:54:43: [META] Recognized game 'czero'; using dllfile 'mp.dll'
> L 03/29/2022 - 12:54:43: [META] Game DLL for 'Counter-Strike:Condition Zero' loaded successfully
> L 03/29/2022 - 12:54:43: [META] ini: Begin reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini
> L 03/29/2022 - 12:54:43: [META] ini: Read plugin config for: <amxmodx_mm.dll>
> L 03/29/2022 - 12:54:43: [META] ini: Finished reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini; Found 1 plugins to load
> L 03/29/2022 - 12:54:43: [META] dll: Loading plugins...
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'Fun': Fun v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'Engine': Engine v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'FakeMeta': FakeMeta v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'MySQL': MySQL v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'CStrike': CStrike v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.8.3-dev+5134 Aug  5 2017, AMX Mod X Dev Team
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'Fun'; already loaded (status=running)
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'fun_amxx.dll'
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'Engine'; already loaded (status=running)
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'engine_amxx.dll'
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'FakeMeta'; already loaded (status=running)
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'fakemeta_amxx.dll'
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'MySQL'; already loaded (status=running)
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'mysql_amxx.dll'
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Not loading plugin 'CStrike'; already loaded (status=running)
> L 03/29/2022 - 12:54:43: [META] ERROR: dll: Failed to load plugin 'cstrike_amxx.dll'
> L 03/29/2022 - 12:54:43: [META] dll: Finished loading 1 plugins
> L 03/29/2022 - 12:54:43: Log file closed
> ```

Very likely you’re loading them in metamod, which isn’t necessary. Just uncomment the ; in modules.ini in the amxx folder, or just let it be and it’ll automatically load itself. Metamod is for metamod plugins such as entmod, amxmodx, and such. The modules for amxx is loaded through amxx

**Comment by HEXAGONENTERTAINMENT** [comment]
If I **uncomment** the ";" would I not then be 'commenting' it? Double negative = positive?

I'm not sure I understand the directory or the entry you're referring to.

Modules.ini is in the config folder, not the amxx folder.  
When you say amxx folder, you mean the amxmodx folder, yes?

*edit***

oh, wait.....   You're telling me to uncomment all of the items that "failed to load" by uncommenting them in the modules.ini., aren't you!? lol.

Contents of my modules.ini below:

```
;;;
; To enable a module, remove the semi-colon (;) in front of its name.
; If it's not here, simply add its name, one per line.
; You don't need to write the _amxx part or the file extension.
;;;

;------------------------------
;Fun - provides extra functions
;------------------------------

fun

;----------------------------------------------------
;Engine - provides engine functions core to Half-Life
;----------------------------------------------------

engine

;-----------------------------------------------------------------
;Fakemeta - provides a massive interface into the Half-Life engine
;-----------------------------------------------------------------

fakemeta

;---------------------------------------------------
;SQL Modules - You can have any number on at a time.
;Use amx_sql_type in sql.cfg to specify the default
;---------------------------------------------------

mysql

;----------------------------------------------
;GeoIP - determines the country of ip addresses
;----------------------------------------------

;geoip

;------------------------------------
;Array - advanced arrays in scripting
;------------------------------------

;array

;--------------------------------
;Sockets - network socket support
;--------------------------------

sockets

;--------------------------
;Regular Expression Support
;--------------------------

;regex

;--------------------------------------------------------
;Counter-Strike adds functions specific to Counter-Strike
;--------------------------------------------------------

cstrike

;-------------------------------------------------------------------------
;nVault - easy method of saving and retrieving data from an external file.
;Most older configs use mySQl instead of this AMXX functionality.
;-------------------------------------------------------------------------

;nvault

;-----------------------------------
;Hamsandwich - AMXX Scripting module
;-----------------------------------

;hamsandwich
```

These are the only two entries in the `czero/addons/metamod/plugins.ini` file.

```
win32 addons/amxmodx/dlls/amxmodx_mm.dll
linux addons/amxmodx/dlls/amxmodx_mm_i386.so
```

**Comment by xLeviNx** [comment]
So if you’re running Linux, run the i386 extension but if you’re running the windows version, just run the .dll extension. 

As for the modules, removing the ; will load it. I’m not sure why it’s loading then unloading, but could just be the metamod doing it, it’s really not a big concern if everything is working as expected

**Comment by xLeviNx** [comment]
Assuming this is fixed and no longer a amx_super issue
