### ISSUE TITLE
amx_joinmessage and amx_leavemessage issue

### ISSUE THREAD

**Issue by HEXAGONENTERTAINMENT** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#7]
# Show the output of the following:
> version
```
Protocol version 48
Exe version 1.0.0.3/Stdio (czero)
Exe build: 19:53:27 Aug  3 2020 (8684)
```

> meta version
```
Metamod v1.21-am  2013-03-15 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Mar 15 2013, 15:20:21  (msc optimized)
ifvers: 5:13
```

> meta list
```
Currently running plugins:
 [  1] AMX Mod X, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  2] Fun, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  3] Engine, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  4] FakeMeta, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  5] MySQL, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org/
 [  6] CStrike, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  7] Ham Sandwich, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  8] CSX, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org/
 [  9] GeoIP, v1.9.0.5294, Jul 12 2021, by AMX Mod X Dev Team, see http://www.amxmodx.org/
9 plugins
```

> amxx version
```
AMX Mod X 1.9.0.5294
Authors: 
         David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko, Felix "SniperBeamer" Geyer
         Jonny "Got His Gun" Bergstrom, Lukasz "SidLuke" Wlasinski
         Christian "Basic-Master" Hammacher, Borja "faluco" Ferrer
         Scott "DS" Ehlert
Compiled: Jul 12 2021, 04:02:45
URL:http://www.amxmodx.org/
Core mode: JIT
```

> amxx plugins 
Currently loaded plugins:
name version author file status
```
[ 1] Admin Base 1.9.0.5294 AMXX Dev Team admin.amxx running
[ 2] Admin Commands 1.9.0.5294 AMXX Dev Team admincmd.amxx running
[ 3] Admin Help 1.9.0.5294 AMXX Dev Team adminhelp.amxx running
[ 4] Multi-Lingual System 1.9.0.5294 AMXX Dev Team multilingual.am running
[ 5] Menus Front-End 1.9.0.5294 AMXX Dev Team menufront.amxx running
[ 6] Commands Menu 1.9.0.5294 AMXX Dev Team cmdmenu.amxx running
[ 7] Players Menu 1.9.0.5294 AMXX Dev Team plmenu.amxx running
[ 8] Maps Menu 1.9.0.5294 AMXX Dev Team mapsmenu.amxx running
[ 9] Plugin Menu 1.9.0.5294 AMXX Dev Team pluginmenu.amxx running
[ 10] Admin Chat 1.9.0.5294 AMXX Dev Team adminchat.amxx running
[ 11] Anti Flood 1.9.0.5294 AMXX Dev Team antiflood.amxx running
[ 12] Scrolling Message 1.9.0.5294 AMXX Dev Team scrollmsg.amxx running
[ 13] Info. Messages 1.9.0.5294 AMXX Dev Team imessage.amxx running
[ 14] NextMap 1.9.0.5294 AMXX Dev Team nextmap.amxx running
[ 15] TimeLeft 1.9.0.5294 AMXX Dev Team timeleft.amxx running
[ 16] Pause Plugins 1.9.0.5294 AMXX Dev Team pausecfg.amxx running
[ 17] Stats Configuration 1.9.0.5294 AMXX Dev Team statscfg.amxx running
[ 18] StatsX 1.9.0.5294 AMXX Dev Team statsx.amxx running
[ 19] HLstatsX CE Ingame Plu 1.6.18 (HL psychonic hlstatsx_comman running
[ 20] Autoresponder/Advertis 0.5 MaximusBrood ad_manager.amxx running
[ 21] AdminListen 2.3x /dev/ urandom adminlisten.amx running
[ 22] Admin Spectator ESP 1.3 KoST admin_spec_esp. running
[ 23] AFK KiSSS 3.0.0 Beta Isobold afkkisss.amxx running
[ 24] Ultimate Gore 1.6 JTP10181 amx_gore_ultima running
[ 25] High Ping Kicker 1.0 Shadow/Bo0m! amx_hpk.amxx running
[ 26] AMX Super Cmd Manager 5.0.2 SuperCentral.co amx_super-cmdma running
[ 27] Amx Super Fun 5.0.2 SuperCentral.co amx_super-fun.a running
[ 28] Amx Super Others 5.0.2 SuperCentral.co amx_super-other running
[ 29] Amx Super Serious 5.0.2 SuperCentral.co amx_super-serio running
[ 30] AMX_Super Menu 5.0.2 SuperCentral.co amx_super-menu. running
[ 31] AMX Bank 1.7 twistedeuphoria amx_bank.amxx running
[ 32] AMXX Spy++ 1.0 [DeathTV] Sid 6. amx_spyplusplus running
[ 33] Automatic knife duel 0.3 JGHG automatic_knife running
[ 34] Last man bets 0.9.4 JGHG lastmanbets_nop running
[ 35] Map Spawns Editor 1.0.16 iG_os Map_Spawns_Edit running
[ 36] Mirror Damage 1.0.0 EKS mirror_damage.a running
[ 37] Team Balancer 1.8b3 Ptahhotep ptb.amxx running
[ 38] Quake Sounds 2.1 hleV quakesounds.amx running
[ 39] HLstatsX Rank 1.8.2 Sneakin' Snake rank.amxx running
[ 40] Reconnect Features 0.2.4 BETA ConnorMcLeod reconnect_featu running
[ 41] Restrict Weapons 1.9.0.5294 AMXX Dev Team restmenu.amxx running
[ 42] Advanced Roll The Dice v2.5 RC 4 Striker roll_the_dice.a running
[ 43] Silly C4 1.2 Cheap_Suit sillyc4.amxx running
[ 44] Player Model 2.13c commonbullet playermodel.amx running
44 plugins, 44 running
```

> status
```
hostname:              THE HEXAGON
version :  48/1.0.0.3 8308 secure  (80)
tcp/ip  :  74.91.123.28:27015
map     :  $2000$ at: 0 x, 0 y, 0 z
players :  8 active (26 max)
```

### Provide error logs from amxmodx/logs/error_  and post them in code tags or upload to either hastebin/pastebin with an appropriate link.

I HAVE NO ERROR LOGS.   I HAD ONE LOG WHEN I WAS FIRST SETTING IT UP, BUT THAT ERROR WAS IDENTIFIED AND DELETED OVER A YEAR AGO.

The current contents of the applicable section in my amx_super.cfg that this issue is related to:
```
// Show HUD message when a player joins the server.
// 0 - Disabled
// 1 - Enabled
//
// Default value: 1
amx_joinmessage_enable 0

// Message to show when a player joins the server.
// Note: %name% & %rankpos% will be replaced with their appropriate values.
// Note: Not used when amx_joinmessage_enable is 0.
// 
// Default value: "%name% has joined!\nEnjoy the Server!\nCurrent Ranking is %rankpos%"
amx_join_message "%name% has entered THE HEXAGON!\nEnjoy the Server!\nCurrent Ranking is %rankpos%"

// Show HUD message when a player leaves the server.
// 0 - Disabled
// 1 - Enabled
//
// Default value: 1
amx_leave_message_enable 0

// Message to show when a player leaves the server.
// Note: %name% & %rankpos% will be replaced with their appropriate values.
// Note: Not used when amx_leavemessage_enable is 0.
// 
// Default value: "%name% has left!\nHope to see you back sometime."
amx_leavemessage "%name% has left The Hexagon!\nWhat a SQUARE!"





**Here is my problem:

When people leave, or enter the server I get the HUD message that they have left or entered, however, the %name% is blank.  It just says:               has left the server.

After some time time trying to figure this out, I finally gave up and just tried to turn it off, (see the entry above showing those options set to "0".

Still, I get a message that:                 has left the server.

Interesting that the part about "Enjoy the server", or "What a SQUARE" do NOT display in this message, but I cannot locate any other plugin that would be in control of messages like these.

Can you help with this?**
```

**Comment by xLeviNx** [comment]
Hey, what version are you using? The regular or colored version?

**Comment by HEXAGONENTERTAINMENT** [comment]
> Hey, what version are you using? The regular or colored version?

I'm not sure what you mean.  I was unaware that there were different versions.
Where would you like me to look to answer this question?

**Comment by xLeviNx** [comment]
https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/releases

Which release did you download and install?

Also any chance you can disable all the plugins except for the default and amx_super and see if the issue persists?

**Comment by HEXAGONENTERTAINMENT** [comment]
While we are on this topic as well, is there any particular reason why I see these errors in the logs so often?

```
L 01/21/2023 - 19:27:47: Log file started (file "logs\L0121208.log") (game "czero") (version "48/1.0.0.3/8308")
L 01/21/2023 - 19:27:47: [META] Metamod v1.21-am  2013-03-15
L 01/21/2023 - 19:27:47: [META] by Will Day <willday@metamod.org>
L 01/21/2023 - 19:27:47: [META]    http://www.metamod.org/
L 01/21/2023 - 19:27:47: [META] compiled: Mar 15 2013, 15:20:21  (msc optimized)
L 01/21/2023 - 19:27:47: [META] engine: swds
L 01/21/2023 - 19:27:47: [META] Recognized game 'czero'; using dllfile 'mp.dll'
L 01/21/2023 - 19:27:47: [META] Game DLL for 'Counter-Strike:Condition Zero' loaded successfully
L 01/21/2023 - 19:27:47: [META] ini: Begin reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini
L 01/21/2023 - 19:27:47: [META] ini: Read plugin config for: <amxmodx_mm.dll>
L 01/21/2023 - 19:27:47: [META] ini: Finished reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini; Found 1 plugins to load
L 01/21/2023 - 19:27:47: [META] dll: Loading plugins...
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'Fun': Fun v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'Engine': Engine v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'FakeMeta': FakeMeta v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'MySQL': MySQL v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'CStrike': CStrike v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Not loading plugin 'Fun'; already loaded (status=running)
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Failed to load plugin 'fun_amxx.dll'
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Not loading plugin 'Engine'; already loaded (status=running)
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Failed to load plugin 'engine_amxx.dll'
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Not loading plugin 'FakeMeta'; already loaded (status=running)
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Failed to load plugin 'fakemeta_amxx.dll'
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Not loading plugin 'MySQL'; already loaded (status=running)
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Failed to load plugin 'mysql_amxx.dll'
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Not loading plugin 'CStrike'; already loaded (status=running)
L 01/21/2023 - 19:27:47: [META] ERROR: dll: Failed to load plugin 'cstrike_amxx.dll'
L 01/21/2023 - 19:27:47: [META] dll: Finished loading 1 plugins
L 01/21/2023 - 19:27:47: Log file closed
```

**Comment by xLeviNx** [comment]
Not related to amx_super, but I think we talked about this before? Modules.ini, you may have removed the semicolon from the modules. You don't need to do that, since they will autoload themselves if it is required. Add the semicolons back and see if that issue persists. 

As for the join team, need the info on the release version you have as well as if anything else is clashing. If you need more direct help, you can message me on discord.

**Comment by HEXAGONENTERTAINMENT** [comment]
> https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/releases
> 
> Which release did you download and install?
> 
> Also any chance you can disable all the plugins except for the default and amx_super and see if the issue persists?

I downloaded a year and a month ago.  I don't recall if it was "color" or not.
I assume if there is a difference between the versions there must be some lines of code somewhere to tell the difference?
Isn't it also strange that there would be such a difference, but it's not reflected in the version number?   That's strange, no?

This server is the primetime server in the evenings.  I can't turn off all my plugins and allow the server to continue to run, especially with a full load, maxed out, in the evenings.     During the day I could get away with it, but then there is nobody in it to see if the error continues when people enter or leave.

**Comment by HEXAGONENTERTAINMENT** [comment]
> Not related to amx_super, but I think we talked about this before? Modules.ini, you may have removed the semicolon from the modules. You don't need to do that, since they will autoload themselves if it is required. Add the semicolons back and see if that issue persists.
> 
> As for the join team, need the info on the release version you have as well as if anything else is clashing. If you need more direct help, you can message me on discord.

I'm not sure how to provide info on the release version if the only way to do so is only to "remember" a download from more than a year ago.   There MUST be a better way to identify a version than that.  ?

So put the semicolons back in front of WHICH modules?

Modules.ini looks like this:

```
;;;
; To enable a module, remove the semi-colon (;) in front of its name.
; If it's not here, simply add its name, one per line.
; You don't need to write the _amxx part or the file extension.
;;;

;------------------------------
;Fun - provides extra functions
;------------------------------

fun

;----------------------------------------------------
;Engine - provides engine functions core to Half-Life
;----------------------------------------------------

engine

;-----------------------------------------------------------------
;Fakemeta - provides a massive interface into the Half-Life engine
;-----------------------------------------------------------------

fakemeta

;---------------------------------------------------
;SQL Modules - You can have any number on at a time.
;Use amx_sql_type in sql.cfg to specify the default
;---------------------------------------------------

mysql

;----------------------------------------------
;GeoIP - determines the country of ip addresses
;----------------------------------------------

;geoip

;------------------------------------
;Array - advanced arrays in scripting
;------------------------------------

;array

;--------------------------------
;Sockets - network socket support
;--------------------------------

sockets

;--------------------------
;Regular Expression Support
;--------------------------

;regex

;--------------------------------------------------------
;Counter-Strike adds functions specific to Counter-Strike
;--------------------------------------------------------

cstrike

;-------------------------------------------------------------------------
;nVault - easy method of saving and retrieving data from an external file.
;Most older configs use mySQl instead of this AMXX functionality.
;-------------------------------------------------------------------------

;nvault

;-----------------------------------
;Hamsandwich - AMXX Scripting module
;-----------------------------------

;hamsandwich
```

**Comment by xLeviNx** [comment]
Unfortunately there isn't due to the fact that I did not distinguish the color chats version.

As for that, put it in front of all of them and then restart the server. See if your issue persists.

**Comment by HEXAGONENTERTAINMENT** [comment]
> Unfortunately there isn't due to the fact that I did not distinguish the color chats version.
> 
> As for that, put it in front of all of them and then restart the server. See if your issue persists.

Ok, thanks.  The server is starting to fill up.  I'll try it now and report back.

Thanks for your help thus far

**Comment by HEXAGONENTERTAINMENT** [comment]
I have changed my modules.ini to the following,....

BUT, ARE YOU SURE THAT **EVERY** MODULE SHOULD BE UNCOMMENTED?

Some of these look like they should have nothing to do with this plugin.
```

;;;
; To enable a module, remove the semi-colon (;) in front of its name.
; If it's not here, simply add its name, one per line.
; You don't need to write the _amxx part or the file extension.
;;;

;------------------------------
;Fun - provides extra functions
;------------------------------

;fun

;----------------------------------------------------
;Engine - provides engine functions core to Half-Life
;----------------------------------------------------

;engine

;-----------------------------------------------------------------
;Fakemeta - provides a massive interface into the Half-Life engine
;-----------------------------------------------------------------

;fakemeta

;---------------------------------------------------
;SQL Modules - You can have any number on at a time.
;Use amx_sql_type in sql.cfg to specify the default
;---------------------------------------------------

;mysql

;----------------------------------------------
;GeoIP - determines the country of ip addresses
;----------------------------------------------

;geoip

;------------------------------------
;Array - advanced arrays in scripting
;------------------------------------

;array

;--------------------------------
;Sockets - network socket support
;--------------------------------

;sockets

;--------------------------
;Regular Expression Support
;--------------------------

;regex

;--------------------------------------------------------
;Counter-Strike adds functions specific to Counter-Strike
;--------------------------------------------------------

;cstrike

;-------------------------------------------------------------------------
;nVault - easy method of saving and retrieving data from an external file.
;Most older configs use mySQl instead of this AMXX functionality.
;-------------------------------------------------------------------------

;nvault

;-----------------------------------
;Hamsandwich - AMXX Scripting module
;-----------------------------------

;hamsandwich
```

**Comment by HEXAGONENTERTAINMENT** [comment]
Maybe instead of figuring it out the hard way you could tell me WHAT would be "in color" if I downloaded the "color" version?

BTW, after uncommenting all of the modules, the message is still coming up when people leave, etc.....

**Comment by xLeviNx** [comment]
> Maybe instead of figuring it out the hard way you could tell me WHAT would be "in color" if I downloaded the "color" version?
> 
> BTW, after uncommenting all of the modules, the message is still coming up when people leave, etc.....

The message issue is different from the other issue you brought up. I am helping you with both. The commenting out the modules fixes the meta load data.

As for the distinction between color and regular, is that your messages and chats are different colors. 
I booted up a server for cs:cz and ran the server vanilla with amx super. I am not running into this issue.

**Comment by HEXAGONENTERTAINMENT** [comment]
Would it help if I took a screenshot in game and attached it here so you can see what I'm referring to?

**Comment by HEXAGONENTERTAINMENT** [comment]
BTW, it looks like the change to modules.ini may have fixed all my error messages:

```
L 01/23/2023 - 17:45:15: Log file started (file "logs\L0123151.log") (game "czero") (version "48/1.0.0.3/8308")
L 01/23/2023 - 17:45:15: [META] Metamod v1.21-am  2013-03-15
L 01/23/2023 - 17:45:15: [META] by Will Day <willday@metamod.org>
L 01/23/2023 - 17:45:15: [META]    http://www.metamod.org/
L 01/23/2023 - 17:45:15: [META] compiled: Mar 15 2013, 15:20:21  (msc optimized)
L 01/23/2023 - 17:45:15: [META] engine: swds
L 01/23/2023 - 17:45:15: [META] Recognized game 'czero'; using dllfile 'mp.dll'
L 01/23/2023 - 17:45:15: [META] Game DLL for 'Counter-Strike:Condition Zero' loaded successfully
L 01/23/2023 - 17:45:15: [META] ini: Begin reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini
L 01/23/2023 - 17:45:15: [META] ini: Read plugin config for: <amxmodx_mm.dll>
L 01/23/2023 - 17:45:15: [META] ini: Finished reading plugins list: c:/servers/hexagon/czero/addons/metamod/plugins.ini; Found 1 plugins to load
L 01/23/2023 - 17:45:15: [META] dll: Loading plugins...
L 01/23/2023 - 17:45:15: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.9.0.5294 Jul 12 2021, AMX Mod X Dev Team
L 01/23/2023 - 17:45:15: [META] dll: Finished loading 1 plugins
L 01/23/2023 - 17:45:15: Log file closed
```

**Comment by HEXAGONENTERTAINMENT** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2922692328

**Comment by xLeviNx** [comment]
https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/releases/tag/5.0.2

Can you install this version?

**Comment by HEXAGONENTERTAINMENT** [comment]
> https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/releases/tag/5.0.2
> 
> Can you install this version?

Were you able to see the screenshot at the link I posted?
If so, were you able to see what I am saying?

Does your response mean that, based on the screenshot, it looks like I have the "color" version of the plugin?

...break...

I downloaded the package at the link you provided.

Is there an "uninstall" instruction that is current?  I want to make sure I am getting every piece of the old install out before I reinstall another version just to have the same problem.

**Comment by HEXAGONENTERTAINMENT** [comment]
OK.  I went through the server, deleted every file and replaced them with the files in the package you linked me to.

I rebooted the server, hopped back in, and now I have more problems than I started with.

1.  Hit markers.   Now when you "wall" someone, you can see if you are walling them because you have a hit marker that displays the damage that you are doing to someone you are shooting at.

2.  Rank info popping up in the bottom right corner of the screen in bright green.   It says things like Player / rank / kills / and 0 deaths.   Always ZERO deaths.  The data in that pop-up is completely incorrect and I have no idea where that info is being pulled from.  One thing is for sure, it's COMPLETELY contradictory to the HLSTATSX data and that thing needs to go away IMMEDIATELY as the server is in the middle of a months-long points tournament and now everyone is going to be flipping out about the stuff that is popping up on the screen.


4.   ---blank-- has left the server.   It's still popping up.  Nothing has changed.  I took this screenshot just now after the full uninstall / reinstall:

(https://steamuserimages-a.akamaihd.net/ugc/2032847057958728589/A3A621EF544C812B75596558739CF1DCE3E67ABB/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)

**Comment by HEXAGONENTERTAINMENT** [comment]
OK, I found the option to disable the HUD for bullet_damage so that should be fixed.

I also found the setting for the stats_marquee so that should be fixed as well.


**So now, I think I'm back to the same thing......   What's up with the join_message and leave_message?**

Also, the writing on the screen, as you can see, is still in color.  The stats are green, the leave_message is pink, etc....

So I'm still trying to figure out WHAT, exactly would be different between the amx_super and the amx_super "color" version.

Everything I see is in color.  So I'm still lost on that aspect.

**Comment by xLeviNx** [comment]
Color version will show a lot of the regular text as colored messages. So everything would have colors basically. Best way to understand is by running the colored version.


Edit:
I see the issue now. Give me a few days to test out what it could be

**Comment by HEXAGONENTERTAINMENT** [comment]
> Edit: I see the issue now. Give me a few days to test out what it could be

Thanks!

**Comment by xLeviNx** [comment]
It's very weird. It works at times, and at times it does not. 
Not sure how to troubleshoot this. Do you happen to have bots on the server as well?

**Comment by xLeviNx** [comment]
[amx_super-others.zip](https://github.com/SuperCentral-Gaming-Community/AMX-Super-5.0.2/files/10528385/amx_super-others.zip)
Try this. Removes join messages all together. You can use an external plugin

**Comment by xLeviNx** [comment]
Marking this as closed since no reply. You can comment on this to reopen or open a new issue

**Comment by HEXAGONENTERTAINMENT** [comment]
Reading this message and downloading the new .zip file now.
I will install it on the server today and let you know what happens.
Thank you for looking into this, so far!

**Comment by HEXAGONENTERTAINMENT** [comment]
The problem appears to have been resolved!

Is there anything else in the code that is different that makes anything else function differently?

**Comment by xLeviNx** [comment]
Nope. Nothing else was changed
