### ISSUE TITLE
Load Error 17

### ISSUE THREAD

**Issue by Fiercetree** [SuperCentral-Gaming-Community/AMX-Super-5.0.2#8]
# Show the output of the following:
> version
Protocol version 48
Exe version 1.0.0.3/Stdio (czero)
Exe build: 19:53:27 Aug  3 2020 (8684)

> meta version
Metamod v1.21.1-am  2013-09-26 (5:13)
by Will Day <willday@metamod.org>
   http://www.metamod.org/
compiled: Sep 26 2013, 17:09:41 -0500 (optimized)
ifvers: 5:13

> meta list
Currently running plugins:
 [  1] AMX Mod X, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  2] YaPB, v4.3.729, Jan 28 2023, by YaPB Project, see https://yapb.jeefo.net/
 [  3] Fun, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  4] Engine, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  5] FakeMeta, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  6] CStrike, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
 [  7] CSX, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org/
 [  8] Ham Sandwich, v1.8.2, Feb 14 2013, by AMX Mod X Dev Team, see http://www.amxmodx.org
8 plugins

> amxx version
AMX Mod X 1.8.2
Authors: 
         David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko, Felix "SniperBeamer" Geyer
         Jonny "Got His Gun" Bergstrom, Lukasz "SidLuke" Wlasinski
         Christian "Basic-Master" Hammacher, Borja "faluco" Ferrer
         Scott "Damaged Soul" Ehlert
Compiled: Feb 14 2013, 00:55:00
URL:http://www.amxmodx.org/
Core mode: JIT

> amxx plugins
[  1] Admin Base              1.8.2       AMXX Dev Team     admin.amxx       running  
 [  2] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
 [  3] Admin Help              1.8.2       AMXX Dev Team     adminhelp.amxx   running  
 [  4] Slots Reservation       1.8.2       AMXX Dev Team     adminslots.amxx  running  
 [  5] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
 [  6] Menus Front-End         1.8.2       AMXX Dev Team     menufront.amxx   running  
 [  7] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
 [  8] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
 [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
 [ 10] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running  
 [ 11] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
 [ 12] Anti Flood              1.8.2       AMXX Dev Team     antiflood.amxx   running  
 [ 13] Scrolling Message       1.8.2       AMXX Dev Team     scrollmsg.amxx   running  
 [ 14] Info. Messages          1.8.2       AMXX Dev Team     imessage.amxx    running  
 [ 15] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
 [ 16] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running  
 [ 17] Nextmap Chooser         1.8.2       AMXX Dev Team     mapchooser.amxx  running  
 [ 18] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running  
 [ 19] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running  
 [ 20] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running  
 [ 21] StatsX                  1.8.2       AMXX Dev Team     statsx.amxx      running  
 [ 22] CS Misc. Stats          1.8.2       AMXX Dev Team     miscstats.amxx   running  
 [ 23] unknown                 unknown     unknown           amx_super-cmdma  bad load 
 [ 24] unknown                 unknown     unknown           amx_super-fun    bad load 
 [ 25] unknown                 unknown     unknown           amx_super-menu   bad load 
 [ 26] unknown                 unknown     unknown           amx_super-other  bad load 
 [ 27] unknown                 unknown     unknown           amx_super-serio  bad load 
27 plugins, 22 running

> status
hostname:  Botsylvania
version :  48/1.0.0.3/Stdio 8684 secure  (80)
tcp/ip  :  108.61.125.101:27015
map     :  awp_wulfburg at: 0 x, 0 y, 0 z
players :  13 active (18 max)

## Add rcon if you're doing it from inside the server, via console. Meaning enter the server, open console. Type your password into rcon_password, and then run the above commands as:

> rcon meta version
> rcon meta list
> rcon amxx version
> rcon amxx plugins
> rcon status

### Provide error logs from amxmodx/logs/error_  and post them in code tags or upload to either hastebin/pastebin with an appropriate link.
( 23) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-cmdmanager.amxx")
( 24) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-fun.amxx")
( 25) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-menu.amxx")
( 26) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-others.amxx")
( 27) Load fails: Load error 17 (invalid file format or version) (plugin "amx_super-serious.amxx")

**Comment by xLeviNx** [comment]
These were compiled against 1.9
You'd have to manually compile them yourself or use the web compiler to compile them. I also suggest upgrading to amxmodx 1.9 as it has much better benefits.

**Comment by Fiercetree** [comment]
Thank you so much! Manually compiling the files resolved it. One last issue, the bullet damage still comes up, even after disabling it in the amx super config. Is there another place to disable it?

**Comment by xLeviNx** [comment]
Very odd. Just check in cvars if its actually 0 also. Also adding the cvar to server.cfg and adding the following line to the bottom will ensure that when the map changes, it should work:

`mapchangecfgfile "server.cfg"`

**Comment by Fiercetree** [comment]
> Very odd. Just check in cvars if its actually 0 also. Also adding the cvar to server.cfg and adding the following line to the bottom will ensure that when the map changes, it should work:
> 
> `mapchangecfgfile "server.cfg"`

I fixed the bullet issue. I used to have a different bullet damage plugin and even though I disabled it in my amxx config file under third party plugins, it was still enabled in my server.cfg. Thanks for all your time and help! All my issues are resolved.

**Comment by xLeviNx** [comment]
Awesome. Happy Gaming
